site_name: 癸酉本石头记后28回
site_description: 白骨如山忘姓氏，无非公子与红妆。
extra_css:
  - css/custom.css
theme:
  name: material
  features:
    - navigation.expand
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
repo_name: vicalloy/the-guiyou-version-of-dream-of-the-red-chamber
repo_url: https://github.com/vicalloy/the-guiyou-version-of-dream-of-the-red-chamber
edit_uri: edit/main/docs/
nav:
  - 封面: index.md
  - 前言: 前言.md
  - 序言:
    - 序一：打开红楼大门的金钥匙: 序一：打开红楼大门的金钥匙.md
    - 序二: 序二.md
  - 正文:
    - 第八十一回 惜昵近公子做良媒 讳笞罚丫鬟结恶党: 第八十一回 惜昵近公子做良媒 讳笞罚丫鬟结恶党.md
    - 第八十二回 王熙凤病求千翼方 林黛玉闷作十独吟: 第八十二回 王熙凤病求千翼方 林黛玉闷作十独吟.md
    - 第八十三回 史太君临终念子孙 王夫人膏肓托儿女: 第八十三回 史太君临终念子孙 王夫人膏肓托儿女.md
    - 第八十四回 薛宝钗弥望金玉缘 史湘云喜得如意郎: 第八十四回 薛宝钗弥望金玉缘 史湘云喜得如意郎.md
    - 第八十五回 痴王孙传信牵奇缘 惭妙尼避情乘游槎: 第八十五回 痴王孙传信牵奇缘 惭妙尼避情乘游槎.md
    - 第八十六回 挑正庶风月断佳偶 祭祖祠清明泣远嫁: 第八十六回 挑正庶风月断佳偶 祭祖祠清明泣远嫁.md
    - 第八十七回 花柳质命断无情兽 绣户女自绝美韶华: 第八十七回 花柳质命断无情兽 绣户女自绝美韶华.md
    - 第八十八回 邢夫人执意寻舛错 王熙凤聪明误此生: 第八十八回 邢夫人执意寻舛错 王熙凤聪明误此生.md
    - 第八十九回 有情人欣遇赏心事 不良妾专煞良辰景: 第八十九回 有情人欣遇赏心事 不良妾专煞良辰景.md
    - 第九十回 林黛玉嬉春待好音 贾元春托梦警天伦: 第九十回 林黛玉嬉春待好音 贾元春托梦警天伦.md
    - 第九十一回 锦衣卫查抄荣宁府 御林军戒严大观园: 第九十一回 锦衣卫查抄荣宁府 御林军戒严大观园.md
    - 第九十二回 家宅乱恶子通强梁 世道艰道人连流寇: 第九十二回 家宅乱恶子通强梁 世道艰道人连流寇.md
    - 第九十三回 山雨近阊阖笼霭晦 风云喧末世漫尘烟: 第九十三回 山雨近阊阖笼霭晦 风云喧末世漫尘烟.md
    - 第九十四回 骨肉泯良女落风尘 贵贱失恶奴劫浮财: 第九十四回 骨肉泯良女落风尘 贵贱失恶奴劫浮财.md
    - 第九十五回 水月庵龄官挞贾蔷 嶽神庙茜雪慰宝玉: 第九十五回 水月庵龄官挞贾蔷 嶽神庙茜雪慰宝玉.md
    - 第九十六回 贾宝玉参无知无识 花袭人信有始有终: 第九十六回 贾宝玉参无知无识 花袭人信有始有终.md
    - 第九十七回 鸳鸯女谮语泄天机 绛珠仙泪尽抛全生: 第九十七回 鸳鸯女谮语泄天机 绛珠仙泪尽抛全生.md
    - 第九十八回 系新绦嗟慰失意人 拾旧帕悲悼寂寞骨: 第九十八回 系新绦嗟慰失意人 拾旧帕悲悼寂寞骨.md
    - 第九十九回 林黛玉还魂证前缘 贾宝玉展裘触旧情: 第九十九回 林黛玉还魂证前缘 贾宝玉展裘触旧情.md
    - 第一百回 邢岫烟魂断大庾岭 赵姨娘命丧平安州: 第一百回 邢岫烟魂断大庾岭 赵姨娘命丧平安州.md
    - 第一百一回 呆霸王惹祸牵旧案 悍妒妇作歹设新谋: 第一百一回 呆霸王惹祸牵旧案 悍妒妇作歹设新谋.md
    - 第一百二回 冷惜春甘伴青灯佛 洁妙玉泥陷瓜洲渡: 第一百二回 冷惜春甘伴青灯佛 洁妙玉泥陷瓜洲渡.md
    - 第一百三回 刘姥姥三进荣国府 贾巧姐二哭大观园: 第一百三回 刘姥姥三进荣国府 贾巧姐二哭大观园.md
    - 第一百四回 毒中毒薛姨妈添病 计上计夏金桂焚身: 第一百四回 毒中毒薛姨妈添病 计上计夏金桂焚身.md
    - 第一百五回 薛宝钗借词含讽谏 王熙凤知命强英雄: 第一百五回 薛宝钗借词含讽谏 王熙凤知命强英雄.md
    - 第一百六回 孤倔王孙悬崖撒手 凄惶红袖秋千传情: 第一百六回 孤倔王孙悬崖撒手 凄惶红袖秋千传情.md
    - 第一百七回 史湘云诉前尘旧梦 贾宝玉淡后事今生: 第一百七回 史湘云诉前尘旧梦 贾宝玉淡后事今生.md
    - 第一百八回 情不情僧遭逢穷途 幻中幻境展演情榜: 第一百八回 情不情僧遭逢穷途 幻中幻境展演情榜.md
  - 附录:
    - 癸酉本石头记前八十回批语摘录: 癸酉本石头记前八十回批语摘录.md

markdown_extensions:
  - footnotes
# extra_javascript:
#   - extra.js
